apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::565257597039:role/eksctl-roboshop-nodegroup-roboshop-NodeInstanceRole-diUUIgqsJ6VC
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::565257597039:user/kranthi
      username: kranthi
kind: ConfigMap
metadata:
  creationTimestamp: "2026-08-10T04:44:19Z"
  name: aws-auth
  namespace: kube-system
  uid: 4ef632e2-1b42-4c66-b317-2e7100246939