apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::565257597039:role/eksctl-roboshop-addon-iamserviceaccount-robos-Role1-yCLHGgNtxLrs
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: aroboshop-mysql-secret-reader
  namespace: roboshop